### ISSUE TITLE
Can you public the trained F theta model?

### ISSUE THREAD

**Issue by Luvata** [NVlabs/PALAVRA#1]
Hi team, very interesting work! I want to play around with this model and I'm looking for the pretrained f theta, can you public it for both reproduction and testing purpose too?

**Comment by NivC** [comment]
Hi Luvata,

Thanks for the interest in our work!
Unfortunately, we cannot release the model weights due to legal issues.
The paper results can be reproduced using the code and instruction in this repo.

Best,
Niv.
